services:
  # Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: fanny-portfolio:prod
    container_name: fanny-portfolio-prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./docker/php/production.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - fanny-portfolio
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  # Nginx Service (Production)
  webserver:
    image: nginx:alpine
    container_name: fanny-portfolio-webserver
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - fanny-portfolio
    depends_on:
      - app

  # MariaDB Service (Production)
  db:
    image: mariadb:latest
    container_name: fanny-portfolio-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_AUTO_UPGRADE: 1
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - fanny-portfolio
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  fanny-portfolio:
    driver: bridge

volumes:
  dbdata:
    driver: local
