version: '3.8'

services:
  # Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: fanny-portfolio:prod
    container_name: fanny-portfolio-app-prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./docker/php/production.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - fanny-portfolio
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

  # Nginx Service (Production)
  webserver:
    image: nginx:alpine
    container_name: fanny-portfolio-webserver-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - fanny-portfolio
    depends_on:
      - app

  # MySQL Service (Production)
  db:
    image: mysql:8.0
    container_name: fanny-portfolio-db-prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/production.cnf:/etc/mysql/my.cnf
    networks:
      - fanny-portfolio

  # Redis Service (Production)
  redis:
    image: redis:alpine
    container_name: fanny-portfolio-redis-prod
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - fanny-portfolio

# Docker Networks
networks:
  fanny-portfolio:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
