services:
  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: fanny-portfolio:dev
    container_name: fanny-portfolio
    restart: unless-stopped
    working_dir: /var/www/html
    command: ["/usr/local/bin/laravel-start.sh"]
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - fanny-portfolio
    depends_on:
      db:
        condition: service_healthy

  # Nginx Service (Development)
  webserver:
    image: nginx:alpine
    container_name: fanny-portfolio-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fanny-portfolio
    depends_on:
      - app

  # MariaDB Service
  db:
    image: mariadb:latest
    container_name: fanny-portfolio-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_AUTO_UPGRADE: 1
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - fanny-portfolio
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # Node.js for development (Vite)
  node:
    image: node:24-alpine
    container_name: fanny-portfolio-node
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html
      - ./docker/scripts/node-start.sh:/usr/local/bin/node-start.sh:ro
    command: ["/bin/sh", "/usr/local/bin/node-start.sh"]
    networks:
      - fanny-portfolio
    depends_on:
      - app

networks:
  fanny-portfolio:
    driver: bridge

volumes:
  dbdata:
    driver: local
